nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/opt:/opt
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/
    links:
        - php:php

php:
    # build: ./php
    build: ./php7
    # image: engine_php7
    ports:
      - "9000:9000"
    links:
      - mysql:mysql
      - memcache:memcache
      - redis:redis
      # - gearman:gearman
    volumes:
      - ~/opt:/opt
      - ~/opt/run:/var/run/mysqld
      # - ~/opt/conf/php:/usr/local/etc/php
      # - ~/opt/conf/php:/usr/local/etc/php-fpm.conf

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/opt/data/mysql:/var/lib/mysql
      - ~/opt/run:/var/run/mysqld
      - ~/opt/data/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Sohpeter123"

memcache:
    build: ./memcache
    command: memcached -m 64
    ports:
      - "11211:11211"

redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ~/opt/run/redis6379.pid:/data/redis6379.pid
      - ~/opt/data/redis:/datas

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8080:80
    environment:
        MYSQL_USERNAME: root
        MYSQL_PASS: "Sohpeter123"
        PMA_HOST: mysql

# gearman:
    # build: ./gearman
    # ports:
    #   - "4730:4730"
    # volumes:
    #   - ~/opt:/opt

# elasticsearch:
#   image: elasticsearch
#   ports:
#     - "9200:9200"
    # - "9300:9300"
